language: r
cache: packages
latex: false
fortran: false
env:
  - _R_CHECK_FORCE_SUGGESTS_=false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - os: osx
      brew_packages: imagemagick
    - os: osx
      brew_packages: imagemagick@6
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
    - dist: trusty
      r_check_args: '--ignore-vignettes'
      r_build_args: '--no-build-vignettes'
      addons:
        apt:
          update: true
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            - r-cran-rgdal
            - libfftw3-dev
            - cargo
            - gsfonts

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts

bioc_packages: EBImage
